# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='user',
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
